---
version: "3.8"

services:

  kafka:
    image: kafka-base:3.4.0
    # build:
    #   context: .
    #   dockerfile: base.Dockerfile
    container_name: kafka
    command: kafka-kraft
    ports:
      - target: 9092
        published: 9092
        mode: host
      - target: 9093
        published: 9093
        mode: host
    volumes:
      - type: bind
        source: ${APPS_LOGS}/kafka
        target: /tmp/logs
    networks:
      - main-overlay-network
    env_file:
      - ${APPS_ENV}/kafka.env
    restart: always


networks:
  main-overlay-network:
    external: true
    driver: overlay
    attachable: true
