---
version: "3.8"

services:

  kafka:
    image: kafka-base:3.4.0
    # build:
    #   context: .
    #   dockerfile: base.Dockerfile
    container_name: kafka
    hostname: kafka
    command: kafka-kraft
    labels:
      autoheal: 'true'
    ports:
      - target: 9092
        published: 9092
        mode: host
      - target: 9093
        published: 9093
        mode: host
    volumes:
      - type: bind
        source: ${APPS_LOGS}/kafka
        target: /tmp/logs
    environment:
      # 16 bytes of a base64-encoded UUID
      KAFKA_CLUSTER_ID: "OiY16813QnOWGJwZ9eX0YQ"
    networks:
      - main-overlay-network
    env_file:
      - ${APPS_ENV}/kafka.env
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always


networks:
  main-overlay-network:
    external: true
    driver: overlay
    attachable: true
